services:
  db:
    build: ./db
    image: alesandocker/inventorit-db:1.0.0
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: inventory_db
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    image: alesandocker/inventorit-backend:1.0.0
    restart: always
    ports:
      - "3000"
    volumes:
      - ./uploads:/app/backend/src/uploads
    environment:
      PORT: 3000
      SERVER_IP: ${SERVER_IP:-localhost}
      ALLOWED_ORIGINS: ${ALLOWED_ORIGINS:-}
      NODE_ENV: ${NODE_ENV:-development}
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: postgrespassword
      DB_NAME: inventory_db
      DB_PORT: 5432
    depends_on:
      - db

  frontend:
    build: ./frontend
    image: alesandocker/inventorit-frontend:1.0.0
    restart: always

  nginx:
    image: nginx:1.28-alpine
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      - frontend

volumes:
  db_data:
